datenbank_physik/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('label/', include('labels.urls')),
    path('', include('public.urls')),
    path('inventory/', include('inventory.urls')),
    path('experiment/', include('experiment_list.urls')),
    path('device/', include('devices.urls')),
    path('bookings/', include('bookings.urls')),
    path('commits/', include('commits.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'datenbank_physik.views.custom_page_not_found'
handler500 = 'datenbank_physik.views.custom_server_error'

devices/urls.py
from django.urls import path, re_path

from . import views

urlpatterns = [
    path('', views.devices_overview, name="devices"),

    path('add/', views.DeviceDocumentCreate.as_view(), name='device_add'),
    path('<int:device_id>/', views.custom_redirect),
    path('<int:pk>/edit/', views.DeviceDocumentUpdate.as_view(), name='device-update'),
    path('<int:pk>/delete/', views.DeviceDelete.as_view(), name='device-delete'),
    path('<int:device_id>/description/', views.device_fullpage, name="device_description"),
    path('<int:device_id>/inventory/', views.device_fullpage, name="device_view"),
    path('<int:device_id>/previous/', views.get_previous_device),
    path('<int:device_id>/next/', views.get_next_device),
    path('<int:device_id>/<str:_>/', views.device_fullpage, name="device_fullpage"),

    path('category/create/', views.location_create, name="location_create"),
    re_path(r'^category/create/(?P<categoryid>\d+)/$', views.location_create, name="location_create_sub"),
    path('category/<int:_>/', views.devices_overview),
    path('category/<int:locationid>/edit/', views.location_edit, name="location_edit"),
    path('category/<int:locationid>/delete/', views.location_delete, name="location_delete"),
]

inventory/urls.py
from django.urls import path, re_path

from . import views

urlpatterns = [
    path('', views.inventory_showAll, name="inventory"),
    path('create/', views.inventory_create, name="inventory_create"),
    re_path(r'^(?P<inventoryid>\d+)/view/$', views.inventory_view, name="inventory_view"),
    re_path(r'^(?P<inventoryid>\d+)/end/$', views.inventory_end, name="inventory_end"),
    re_path(r'^(?P<inventoryid>\d+)/delete/$', views.inventory_delete, name="inventory_delete"),
    path('<int:inventoryid>/remove/<int:deviceid>', views.inventory_remove_device, name="inventory_remove_device"),

    # AJAX
    path('change_device/', views.inventory_change_device, name="inventory_change_device"),
    path('fullpage/', views.fullpage_inventory, name="fullpage_inventory"),

    path('loan/', views.loan_showAll, name="loan"),
    path('loan/create/', views.loan_create, name="loan_create"),
    re_path(r'^loan/(?P<loanid>\d+)/return/$', views.loan_return, name="loan_return"),
    re_path(r'^loan/(?P<loanid>\d+)/view/$', views.loan_view, name="loan_view"),
    re_path(r'^loan/(?P<loanid>\d+)/delete/$', views.loan_delete, name="loan_delete"),
]

labels/urls.py
from django.urls import path, re_path

from . import views

urlpatterns = [
    path('', views.label_showAll, name="label"),
    path('create/', views.label_create, name="label_create"),
    re_path(r'^(?P<labelid>\d+)/edit/$', views.label_edit, name="label_edit"),
    re_path(r'^(?P<labelid>\d+)/delete/$', views.label_delete, name="label_delete"),

    path('color/', views.label_color, name="color_edit"),
    re_path(r'^color/(?P<colorid>\d+)/delete/$', views.color_delete, name="color_delete"),

    re_path(r'^(?P<labelid>\d+)/view/$', views.label_view, name="label_view"),
]

devices/models.py
from django.db import models

# Create your models here.

inventory/models.py
import os

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.core.cache import cache
from django.db import models
from django.db.models import signals
from django.dispatch import receiver
from django.http import request
from django.utils import timezone

from public.models import Device, Location, Document

User = get_user_model()


class Loan(models.Model):
    """DB model for loans"""
    startdate = models.DateTimeField(auto_now_add=True)
    enddate = models.DateTimeField(null=True, blank=True)
    loaned_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    loaned_to = models.CharField(max_length=255, blank=True, null=True)
    active = models.BooleanField(default=False)

    LOAN_CHOICES = (
        ('loan', "Verleih"),
        ('repair', "E-Werkstatt"),
    )
    type = models.CharField(max_length=255, choices=LOAN_CHOICES)
    comment = models.TextField(blank=True, null=True)
    info = models.FileField(upload_to='', blank=True, null=True)

    def __str__(self):
        return self.comment

    def delete(self, *args, **kwargs):
        if self.info:
            try:
                os.remove(os.path.join(settings.MEDIA_ROOT, self.info.name))
            except Exception as e:
                messages.add_message(request, messages.ERROR, e)

        super(Loan, self).delete(*args, **kwargs)

    def add_device(self, id, amount, comment):
        device = Device.objects.get(id=id)
        if self.type == 'loan':
            device.add_loan(amount)
        else:
            device.add_repair(amount)
        self.loanitem_set.add(LoanItem(item=device, amount=amount, comment=comment), bulk=False)


    def start(self, user):
        self.active = True
        self.loaned_by = user
        self.save()

    def end_loan(self):
        self.active = False
        for l in self.loanitem_set.all():
            if self.type == 'loan':
                l.item.remove_loan(l.amount)
            else:
                l.item.remove_repair(l.amount)
        self.enddate = timezone.now()
        self.save()

    def is_due(self):
        if self.type == 'loan':
            return self.enddate <= timezone.now()
        return False


class LoanItem(models.Model):
    """DB model for loan instances"""
    item = models.ForeignKey(Device, on_delete=models.CASCADE, null=True)
    amount = models.IntegerField()
    comment = models.CharField(max_length=255, blank=True, null=True)
    loan = models.ForeignKey(Loan, on_delete=models.CASCADE)

    def __str__(self):
        return self.item.name


class Inventory(models.Model):
    """DB model for inventories"""
    name = models.CharField(max_length=255, blank=True, null=True)
    startdate = models.DateTimeField(auto_now_add=True)
    enddate = models.DateTimeField(null=True, blank=True)
    active = models.BooleanField(default=False)
    started_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        """Returns inventory name as a string"""
        return self.name

    def start(self, user):
        """Starting an inventory"""
        self.active = True
        self.started_by = user
        self.save()

    def end(self):
        """Ending an inventory"""
        self.active = False
        self.enddate = timezone.now()
        self.save()

    def add(self, device):
        """Adding a device to an active inventory"""
        item = self.inventoryitem_set.filter(item=device)
        if not item.exists():
            self.inventoryitem_set.add(InventoryItem(item=device), bulk=False)

    def remove(self, device):
        """Removing a device from an active inventory"""
        items = self.inventoryitem_set.filter(item=device).delete()

    def has_device(self, device):
        """Returns true if the device is catalogued in this inventory"""
        if self.inventoryitem_set.filter(item=device.id):
            return True
        else:
            return False

    def clear(self):
        """Removes all catalogued devices from this inventory"""
        self.inventoryitem_set.all().delete()


class InventoryItem(models.Model):
    """DB model for an inventory instance"""
    item = models.ForeignKey(Device, on_delete=models.CASCADE, null=True)
    info = models.TextField(blank=True, null=True)
    inventory = models.ForeignKey(Inventory, on_delete=models.CASCADE)

    def __str__(self):
        """Returns device name as a string"""
        return self.item.name

inventory/forms.py
from django import forms

from public.models import Device
from .models import Inventory, InventoryItem, Loan, LoanItem


def getDeviceToken():
    """Appends device id to device name and returns formatted list of device names"""
    device_list = list(Device.objects.all().values_list('id', 'name'))
    device_list = [list(x) for x in device_list]
    for d in device_list:
        d[1] = str(d[0]) + " " + d[1]
    device_list.append([0, 'Gerät auswählen'])
    device_list.sort(key=lambda x: x[0])
    return device_list


class CreateInventoryForm(forms.ModelForm):
    """Form for creating a new inventory"""
    class Meta:
        model = Inventory
        fields = ('name',)


class EditInventoryForm(forms.ModelForm):
    """Form for editing an existing inventory"""
    name = forms.CharField(
        label = "Bemerkung",
        widget=forms.TextInput(
            attrs={
                   'placeholder': "Nutzername..."
            }
        )
    )

    items = forms.ModelMultipleChoiceField(
        label="Inventierte Geräte",
        queryset=InventoryItem.objects.all(),
        widget=forms.SelectMultiple()
    )

    class Meta:
        model = Inventory
        fields = ('name', 'items')


class CreateLoanForm(forms.ModelForm):
    enddate = forms.DateTimeField(
        label="Rückgabe",
        widget=forms.DateTimeInput(
            attrs={
                'type': 'date',
            }
        ),
    )

    loaned_to = forms.CharField(
        label="Verliehen an",
        widget=forms.TextInput(
            attrs={
                'placeholder': "Verliehen an...",
            }
        )
    )

    comment = forms.CharField(
        label="Zusatzinformation",
        required=False,
        widget=forms.Textarea(
            attrs={
                'placeholder': "Zusatzinformation...",
            }
        ),
    )

    type = forms.ChoiceField(
        choices=Loan.LOAN_CHOICES,
        label="Typ",
        widget=forms.Select(
            attrs={
                'onChange': "switchType(this);",
            }
        ),
        initial='loan',
    )

    info = forms.ImageField(
        required=False,
        label="Bild",
        widget=forms.FileInput(
        )
    )

    field_order = ['type', 'loaned_to', 'enddate', 'comment', 'info']

    class Meta:
        model = Loan
        fields = ('loaned_to', 'type', 'comment', 'enddate', 'info',)


class LoanReturnForm(forms.ModelForm):



    class Meta:
        model = Loan
        fields = ('comment',)


class LoanItemForm(forms.Form):
    item = forms.ChoiceField(
        choices=getDeviceToken(),
        # empty_label="Gerät auswählen",
        widget=forms.Select(
            attrs={
                'class': "device_select",
                'placeholder': "Geräte auswählen..."
            }
        ),
    )

    amount = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={
                'min': 1,
                'max': 100,
            }
        ),
        disabled=True,
    )

    comment = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'placeholder': "Anmerkung...",
                'id': "loanitem_comment",
            }
        ),
        disabled=True,
    )

templates/inventory/device.html
{{ content }}

templates/inventory/inventory.html
{% extends "base/base.html" %}
{% load user_tags %}

{% block page_buttons %}
    {% if user|has_group:"Schreiben - Inventur" %}
        {% if inventory.active %}
            <button type="submit" id="confirm_deletion" value="{% url 'inventory_end' inventory.id %}"
                    onclick="customConfirm(this, 'Inventur wirklich beenden?', 'Beenden')">{% include 'icons/ic_publish_24px.svg' %}
                Beenden
            </button>
        {% else %}
            <button type="submit" id="confirm_deletion" value="{% url 'inventory_delete' inventory.id %}"
                    onclick="customConfirm(this, 'Inventur wirklich löschen?', 'Löschen')">{% include 'icons/delete.svg' %}
                Löschen
            </button>
        {% endif %}
    {% endif %}
{% endblock %}

{% block content %}
    {% include 'modal/delete.html' %}
    <div class="inventory_container">
        <h1>Übersicht</h1>
        <div class="head">
            <strong>Gestartet von:</strong><small>{{ inventory.started_by.username }}</small>

            <strong>Startdatum:</strong><small>{{ inventory.startdate|date:"d. F Y" }}
            um {{ inventory.startdate|date:"H:i" }}</small>
            <strong>Anmerkung:</strong><small>{{ inventory.name }}</small>
            <strong>Status:</strong>
            <small>
                {% if inventory.enddate %}
                    Beendet am {{ inventory.enddate|date:"d. F Y" }} um {{ inventory.enddate|date:"H:i" }}
                {% else %}
                    In Durchführung
                {% endif %}
            </small>
        </div>

        <div class="device_show" onclick="toggleDeviceList($(this), $('#inventory_hit'))">
            {% include 'icons/arrow_forward-24px.svg' %}
            <h2>Inventierte Geräte</h2>
        </div>
        <table id="inventory_hit" class="alternating_list" style="display: none">
            <thead>
            <tr>
                <th scope="col">Geräte ID</th>
                <th scope="col">Bezeichnung</th>
                <th scope="col">Zusatzinformationen</th>
                <th scope="col">Aktionen</th>
            </tr>
            </thead>
            <tbody>
            {% for inventoryitem in inventory.inventoryitem_set.all %}
                {% include 'inventory/item.html' with device=inventoryitem.item delete=True %}
            {% endfor %}
            </tbody>
        </table>

        <div class="device_show" onclick="toggleDeviceList($(this), $('#inventory_miss'))">
            {% include 'icons/arrow_forward-24px.svg' %}
            <h2>Nicht inventierte Geräte</h2>
        </div>
        <table id="inventory_miss" style="display: none;" class="alternating_list">
            <thead>
            <tr>
                <th scope="col">Geräte ID</th>
                <th scope="col">Bezeichnung</th>
                <th scope="col">Aktionen</th>
            </tr>
            </thead>
            <tbody>
            {% for device in misses %}
                {% include 'inventory/item.html' %}
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/inventory/item.html
{% load user_tags %}

<tr>
    <td data-label="Geräte ID">{{ device.id }}</td>
    <td data-label="Bezeichnung">{{ device }}</td>
    {% if inventoryitem %}
        <td data-label="Zusatzinformationen">
            {{ inventoryitem.info|default:"<i>Keine zusätzliche Information</i>" }}
        </td>
    {% endif %}
    <td data-label="Aktionen">
        <div>
            <a href="{% url 'device_view' device.id %}" class="blue underline_button">{% include 'icons/ic_eye_24px.svg' %}Ansehen</a>
            {% if not inventory.enddate and delete and user|has_group:"Schreiben - Inventur" %}
                <button id="confirm_deletion" value="{% url "inventory_remove_device" inventory.id device.id %}"
                        class="red underline_button"
                        onclick="confirmDeletion(this)">
                    {% include 'icons/x.svg' %}Entfernen
                </button>
            {% endif %}
        </div>
    </td>
</tr>

templates/inventory/loan.html
{% extends "base/base.html" %}
{% load user_tags %}

{% block page_buttons %}
    {% if user|has_group:"Schreiben - Verleih" %}
        {% if loan.active %}
            <button type="submit" id="confirm_deletion" value="{% url 'loan_return' loan.id %}"
                    onclick="customConfirm(this, 'Verleih wirklich zurückgeben?', 'Rückgabe')">{% include 'icons/ic_publish_24px.svg' %}
                Rückgabe
            </button>
        {% else %}
            <button type="submit" id="confirm_deletion" value="{% url 'loan_delete' loan.id %}"
                    onclick="customConfirm(this, 'Verleih wirklich löschen?', 'Löschen')">{% include 'icons/delete.svg' %}
                Löschen
            </button>
        {% endif %}
    {% endif %}
{% endblock %}

{% block content %}
    {% include 'modal/delete.html' %}
    <div class="inventory_container">
        <h1>Übersicht</h1>
        <div class="head">
            <strong id="started_by">Verliehen von:</strong><small>{{ loan.loaned_by.username }}</small>
            <strong>Verliehen an:</strong>
            <small>
                {% if loan.type == 'repair' %}<i>&nbsp;E-Werkstatt</i>
                {% else %}{{ loan.loaned_to }}{% endif %}
            </small>
            <strong>Verleihdatum:</strong><small>{{ loan.startdate|date:"d. F Y" }}
            um {{ loan.startdate|date:"H:i" }}</small>
            <strong>Rückgabedatum:</strong>
            <small>
                {% if loan.type == 'repair' %}<i>&nbsp;in Reparatur</i>
                    {% else %}{{ loan.enddate|date:"d. F Y" }} um {{ loan.enddate|date:"H:i" }}{% endif %}
            </small>
            <strong>Status:</strong>
            <small>
                {% if loan.active %}
                    {% if loan.type == 'loan' %}
                        {% if loan.is_due %}
                            Überfällig seit {{ loan.enddate|timesince:current_time }}
                        {% else %}
                            Rückgabe in {{ current_time|timesince:loan.enddate }}
                        {% endif %}
                    {% else %}
                        In Reparatur seit {{ loan.startdate|timesince:current_time }}
                    {% endif %}
                {% else %}
                    Zurückgegeben
                {% endif %}
            </small>
        </div>

        {% if loan.comment %}
            <h1>Anmerkung:</h1><br>
                <span>{{ loan.comment }}</span>
        {% endif %}
        {% if loan.info %}
            <h1>Infobild:</h1><br>
            <div class="file_item">
                <div class="file_item_text">
                    {{ loan.info.name }}
                </div>
                <a>
                    <div class="file_image_hover">
                        {% include 'modal/image.html' with src=loan.info.url caption=loan.info.name %}
                    </div>
                </a>
            </div>
        {% endif %}
        {% if loan.loanitem_set.all|length > 0 %}
            <div class="device_show" onclick="toggleDeviceList($(this), $('#device_list'))">
            {% include 'icons/arrow_forward-24px.svg' %}
            <h2>Verliehene Geräte</h2>
        </div>
            <table id="device_list" class="alternating_list" style="display: none">
                <thead>
                <tr>
                    <th scope="col">Geräte ID</th>
                    <th scope="col">Bezeichnung</th>
                    <th scope="col">Anzahl</th>
                    <th scope="col">Bemerkung</th>
                    <th scope="col">Aktionen</th>
                </tr>
                </thead>
                <tbody>
                {% for item in loan.loanitem_set.all %}
                    <tr>
                        <td data-label="Geräte ID">{{ item.item.id }}</td>
                        <td data-label="Bezeichnung">{{ item.item.name }}</td>
                        <td data-label="Anzahl">{{ item.amount }}</td>
                        <td data-label="Bemerkung">{{ item.comment|default:"<i>Keine Bemerkung</i>" }}</td>
                        <td data-label="Aktionen">
                            <a href="{% url 'device_view' item.item.id %}" class="blue underline_button">{% include 'icons/ic_eye_24px.svg' %}Ansehen</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        {% endif %}
    </div>
{% endblock %}

templates/inventory/loan_form.html
{% extends "base/base.html" %}
{% load define_action %}

{% block content %}
    <form id="loan_form" method="POST" enctype="multipart/form-data" onsubmit="return (typeof submitted == 'undefined') ? (submitted = true) : !submitted">
        <div class="content_container card form_container" style="border-bottom-left-radius: 0; border-bottom-right-radius: 0">
            {% csrf_token %}
            {% for field in form.visible_fields %}
                <div class="content_container card form_container input_field" id="{{ field.name }}">
                    {{ field.label_tag }}<br/>
                    {{ field }}<br/>
                    {% if field.errors %}
                        <div class="alert alert-danger">
                            <strong>{{ field.errors|escape }}</strong>
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
        </div>

        <input type="hidden" name="devices" id="device_select" value=""/>
        <table class="alternating_list">
            <thead>
            <tr>
                <th scope="col">Gerät</th>
                <th scope="col">Anzahl</th>
                <th scope="col">Anmerkung</th>
                <th scope="col">Aktionen</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td data-label="Gerät">
                    {{ loanform.item }}
                </td>
                <td data-label="Anzahl">{{ loanform.amount }}</td>
                <td data-label="Anmerkung">{{ loanform.comment }}</td>
                <td data-label="Aktionen">
                    <button type="button" id="add_loan_item" class="button" onclick="addLoanItem()" disabled>Gerät hinzufügen</button>
                </td>
            </tr>
            <tr id="loanitem_anchor" style="display: none"></tr>
            </tbody>
        </table>
        <button id="loanform_submit_button" type="submit" onclick="$('#device_select').val(JSON.stringify(selected_devices))">
            {% include 'icons/ic_publish_24px.svg' %} Speichern
        </button>
    </form>
{% endblock %}

{% block javascripts %}
    {{ available|json_script:"available" }}
    <script>

        $("#loan_form").submit(function () {
            $("#loanform_submit_button").attr("disabled", true);
            return true;
        });

        let today = new Date();
        let calendar = flatpickr($("#id_enddate"), {
            enableTime: true,
            dateFormat: "d.m.Y H:i",
            time_24hr: true,
            minDate: today,
            minuteIncrement: 1,
        });

        const available = JSON.parse(document.getElementById('available').textContent);

        $(document).ready(function () {
            const none_available = available.filter(a => a[1] == 0);
            none_available.forEach(function (e) {
                $("#id_item>option[value=" + e[0] + "]").attr('disabled', 'disabled');
            })
        })

        $('#id_amount').on('input', function (e) {
            const val = $('#id_item').val();
            if (val != 0) {
                const device_available = available.filter(a => a[0] == val)[0][1];

                if (e.currentTarget.value > device_available)
                    e.currentTarget.value = device_available;
                if (e.currentTarget.value < 1)
                    e.currentTarget.value = 1;
            }
            const button = document.getElementById('add_loan_item');
            if (val > 0)
                button.disabled = false;
        })

        $('#id_item').change(function () {
            const val = $('#id_item').val();
            const button = document.getElementById('add_loan_item');
            const amount_field = $('#id_amount');
            const comment_field = $('#loanitem_comment');
            if (val != 0) {
                const device_available = available.filter(a => a[0] == val)[0][1];
                amount_field.val('');
                amount_field.attr('max', device_available);
                amount_field.attr('placeholder', device_available + " verfügbar");

                amount_field.prop("disabled", false);
                comment_field.prop("disabled", false);
            } else {
                amount_field.val('');
                amount_field.attr('placeholder', "");
                amount_field.prop("disabled", true);
                comment_field.prop("disabled", true);
            }
            button.disabled = true;
        })

        const LoanItem = ({id, device, amount, comment}) => `
        {% include 'inventory/loanitem.html' %}`;

        function deleteLoanItem(event) {
            const id = event.value;
            event.parentElement.parentElement.remove();
            selected_devices = selected_devices.filter(item => item.id != id);
            $("#id_item>option[value=" + id + "]").removeAttr('disabled');
        }

        $(document).ready(function () {
            $('#id_item').select2();
        });

        function toggleFormAtts(field, visible, required) {
            if (visible == false) {
                if (required) field.prop('required', false);
                field.parent().hide();
            } else {
                field.val('');
                if (required) field.prop('required', true);
                field.parent().show();
            }
        }

        function returnDate() {
            var dd = today.getDate();
            var mm = today.getMonth() + 1; //January is 0!
            var yyyy = today.getFullYear();
            if (dd < 10) {
                dd = '0' + dd
            }
            if (mm < 10) {
                mm = '0' + mm
            }
            return yyyy + '-' + mm + '-' + dd;
        }

        function switchType(event) {
            const val = event.value;
            const loan = $('#id_loaned_to');
            const enddate = $('#id_enddate');
            const info = $('id_#info');
            if (val == 'repair') {
                calendar.destroy();
                toggleFormAtts(loan, false, true);
                loan.val('repair');
                enddate.prop('type', 'text');
                enddate.val(returnDate());
                toggleFormAtts(enddate, false, true);
                toggleFormAtts(info, false, false);

            } else {
                calendar = flatpickr($("#id_enddate"), {
                    enableTime: true,
                    dateFormat: "d.m.Y H:i",
                    time_24hr: true,
                    minDate: today,
                });
                toggleFormAtts(loan, true, true);
                toggleFormAtts(enddate, true, true);
                toggleFormAtts(info, true, false);
            }
        }

        let selected_devices = []

        function addLoanItem() {
            const device = $('#id_item option:selected');
            const amount = $('#id_amount').val();
            let comment = $('#loanitem_comment').val();

            let data = {
                "id": device.val(),
                "device": escapeUserHtml(device.text()),
                "amount": amount,
                "comment": escapeUserHtml(comment),
            };

            let save_data = JSON.parse((JSON.stringify(data)));
            selected_devices.push(save_data);

            if (comment == '') {
                data['comment'] = "<i>Keine Anmerkung</i>";
            }

            $('#loanitem_anchor').after([data].map(LoanItem).join(''));
            $('#id_item').val(0).trigger('change');
            $('#loanitem_comment').val('');

            $("#id_item>option[value=" + device.val() + "]").attr('disabled', 'disabled');
        }

        function render(props) {
            return function (tok, i) {
                return (i % 2) ? props[tok] : tok;
            };
        }
    </script>
{% endblock %}

templates/inventory/loanitem.html
<tr id="${id}">
    <td data-label="Gerät">${device}</td>
    <td data-label="Anzahl">${amount}</td>
    <td data-label="Kommentar">${comment}</td>
    <td data-label="Aktionen">
        <button type="button" class="red underline_button" onclick="deleteLoanItem(this)" value="${id}">
            {% include 'icons/x.svg' %} Entfernen</button>
    </td>
</tr>