accounts/urls.py
from django.urls import path, re_path

from public import views as public
from . import views

urlpatterns = [
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),

    path('profile/', views.profile, name="profile"),
    path('profile/password', views.profile_password, name="profile_password"),

    path('user/', views.user_showAll, name="user"),
    path('user/create/', views.registerPage, name="user_create"),
    re_path(r'^user/(?P<userid>\d+)/delete$', views.user_delete, name="user_delete"),
    re_path(r'^user/(?P<userid>\d+)/edit$', views.user_edit, name="user_edit"),
    re_path(r'^user/(?P<userid>\d+)/edit/password$', views.user_edit_password, name="user_edit_password"),

    path('', public.welcome, name="home"),

    path('user/rights/', views.edit_rights, name="rights_edit"),
    re_path(r'^user/rights/(?P<presetid>\d+)/delete$', views.preset_delete, name="preset_delete"),
    path('user/color/', views.user_color, name="user_color_edit"),
    re_path(r'^user/color/(?P<colorid>\d+)/delete$', views.user_color_delete, name="user_color_delete"),
]

datenbank_physik/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('label/', include('labels.urls')),
    path('', include('public.urls')),
    path('inventory/', include('inventory.urls')),
    path('experiment/', include('experiment_list.urls')),
    path('device/', include('devices.urls')),
    path('bookings/', include('bookings.urls')),
    path('commits/', include('commits.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'datenbank_physik.views.custom_page_not_found'
handler500 = 'datenbank_physik.views.custom_server_error'

labels/urls.py
from django.urls import path, re_path

from . import views

urlpatterns = [
    path('', views.label_showAll, name="label"),
    path('create/', views.label_create, name="label_create"),
    re_path(r'^(?P<labelid>\d+)/edit/$', views.label_edit, name="label_edit"),
    re_path(r'^(?P<labelid>\d+)/delete/$', views.label_delete, name="label_delete"),

    path('color/', views.label_color, name="color_edit"),
    re_path(r'^color/(?P<colorid>\d+)/delete/$', views.color_delete, name="color_delete"),

    re_path(r'^(?P<labelid>\d+)/view/$', views.label_view, name="label_view"),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import PermissionsMixin, Group
from django.db import models
from django.utils.translation import gettext_lazy as _

from labels.models import Color


class PermissionPreset(models.Model):
    """DB model for presets"""
    name = models.CharField(
        _('preset name'),
        unique=True,
        max_length=80,
    )

    groups = models.ManyToManyField(Group)

    def __str__(self):
        """Returns presets name as a sring"""
        return self.name

    def getGroups(self):
        """Gets groups of the preset"""
        return self.groups


class User(AbstractUser):
    """DB model for users"""
    email = models.EmailField(
        _('email address'),
        unique=False,
        blank=True,
    )

    preset = models.ForeignKey(PermissionPreset, on_delete=models.SET_NULL, null=True)
    color = models.ForeignKey(Color, on_delete=models.SET_NULL, null=True)

    def get_color(self):
        return self.color.color if self.color else '#b3b3b3'

    def hasGroup(self, group):
        """Returns true if a given user is in a certain group"""
        return self.groups.filter(name=group).exists()

accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404
from django.shortcuts import render

from labels.utilities import *
from . import forms
from .decorators import *
from .models import *
from .utilities import *

# application wide declarations
User = get_user_model()  # Returns the custom user model defined in models.py


@login_required(login_url='login')
@allowed_users(allowed_roles=['Schreiben - Nutzer'], url='user')
def registerPage(request):
    """Creating a new user"""
    groups = list(Group.objects.all().values('id', 'name'))
    form = forms.CreateUserForm()
    if request.method == 'POST':
        form = forms.CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            addGroupsToUser(form.data['groups'], user)

            if form.data['preset'] != '':
                updateUserPreset(user)

            return redirect('user')

    context = {
        'form': form,
        'main_title': "Nutzer erstellen",
        'page_buttons': [["Rechte bearbeiten", 'rights_edit', 'icons/key-fill.svg'],
                         ["Farben verwalten", 'user_color_edit', 'icons/palette.svg']],
        'group_presets': getGroupPresets(),
        'js_script': 'js/select_permission_presets.js',
        'groups': groups,
        'color_data': buildColorData('user'),
    }
    return render(request, 'accounts/user_form.html', context)


@unauthenticated_user
def loginPage(request):
    """Login"""
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        next = request.POST.get('next')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect(next if next is not None else 'home')
        else:
            messages.error(request, "Nutzername oder Passwort inkorrekt!")

    context = {
        'main_title': "Login",
    }
    return render(request, 'accounts/login.html', context)


def logoutUser(request):
    """Logout"""
    current_user = request.user
    logout(request)
    response = redirect('home')
    response.delete_cookie('comment_category')

    messages.success(request, f"Nutzer {current_user.username} erfolgreich ausgeloggt.")

    return response


@login_required(login_url='login')
@allowed_users(allowed_roles=['Lesen - Nutzer'])
def user_showAll(request):
    """List of all users"""
    user_list = User.objects.all()

    page_buttons = []
    buttons = []
    if request.user.hasGroup("Schreiben - Nutzer"):
        page_buttons.append(["Neuer Nutzer", 'user_create', 'icons/ic_person_add_24px.svg'])
        page_buttons.append(["Rechte bearbeiten", 'rights_edit', 'icons/key-fill.svg'])

        buttons.append(["Bearbeiten", 'blue', 'user_edit', 'icons/pencil-fill.svg']),
        buttons.append(["Passwort ändern", 'blue', 'user_edit_password', 'icons/key-fill.svg']),
        buttons.append(["Löschen", 'red', 'user_delete', 'icons/person-x-fill.svg'])

    context = {
        'user_list': user_list,
        'main_title': "Nutzer",
        'page_buttons': page_buttons,
        'buttons': buttons,
    }
    return render(request, 'accounts/user_list.html', context)


@login_required(login_url='login')
@allowed_users(allowed_roles=['Schreiben - Nutzer'], url='user')
def user_edit(request, userid):
    """Editing a user"""
    groups = list(Group.objects.all().values('id', 'name'))
    # get the user object from User model with the given id
    try:
        current_user = User.objects.get(id=userid)
    except ObjectDoesNotExist as e:
        raise Http404
    # get list of groups of current user
    initial_groups = sorted(list(current_user.groups.all().values('id', 'name')), key=lambda k: k['name'])

    if request.method == 'POST':
        form = forms.ChangeUserForm(request.POST, instance=current_user)
        if form.is_valid():
            user = form.save()
            user.groups.clear()
            addGroupsToUser(form.data['groups'], user)

            if form.data['preset'] != '':
                updateUserPreset(user)

            messages.success(request, f"Nutzer {user.username} erfolgreich geändert.")
            return redirect('user')
    else:
        form = forms.ChangeUserForm(instance=current_user)

    context = {
        'form': form,
        'userid': userid,
        'main_title': f"Nutzer {current_user.username} bearbeiten",
        'page_buttons': [["Rechte bearbeiten", 'rights_edit', 'icons/key-fill.svg'],
                         ["Farben verwalten", 'user_color_edit', 'icons/palette.svg']],
        'group_presets': getGroupPresets(),
        'js_script': 'js/select_permission_presets.js',
        'groups': groups,
        'initial': initial_groups,
        'color_data': buildColorData('user'),
    }
    return render(request, 'accounts/user_form.html', context)


@login_required(login_url='login')
@allowed_users(allowed_roles=['Schreiben - Nutzer'], url='user')
def user_edit_password(request, userid):
    """Editing a user password"""
    try:
        if request.user.id == userid:
            current_user = request.user
        else:
            current_user = User.objects.get(id=userid)
    except ObjectDoesNotExist as e:
        raise Http404

    if request.method == 'POST':
        form = forms.ChangePasswordForm(current_user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)

            messages.success(request, f"Passwort von {user.username} erfolgreich geändert.")
            return redirect('user')
    else:
        form = forms.ChangePasswordForm(current_user)

    context = {'form': form,
               'main_title': f"Passwort von {current_user.username} bearbeiten",
               }
    return render(request, 'accounts/user_form.html', context)


@login_required(login_url='login')
@allowed_users(allowed_roles=['Schreiben - Nutzer'], url='user')
def edit_rights(request):
    """Editing rights of a preset"""
    groups = list(Group.objects.all().values('id', 'name'))

    message = None

    if request.method == 'POST':
        form = forms.ChangePresetForm(request.POST)
        presetid = form.data['preset']
        # check if preset already exists, if so overwrite it, if not create new one
        if presetid != '':
            preset = PermissionPreset.objects.get(id=presetid)
            form = forms.ChangePresetForm(request.POST, instance=preset)
            message = f"Preset {preset.name} erfolgreich geändert."
        else:
            form = forms.ChangePresetForm(request.POST)

        if form.is_valid():
            preset = form.save()
            groups = form.data['groups']
            preset.groups.clear()
            if groups != '':
                groups = json.loads(groups)
                for g in groups:
                    preset.groups.add(g.get('value'))

            updateUserRights(preset)

            if message is None:
                message = f"Preset {preset.name} erfolgreich erstellt."
            messages.success(request, message)

            return redirect('user')
    else:
        form = forms.ChangePresetForm()

    context = {'form': form,
               'main_title': "Rechte bearbeiten",
               'group_presets': getGroupPresets(),
               'js_script': 'js/select_permission_presets.js',
               'groups': groups,
               }
    return render(request, 'accounts/user_form.html', context)


@login_required(login_url='login')
@allowed_users(allowed_roles=['Schreiben - Nutzer'], url='user')
def preset_delete(request, presetid):
    """Delete a preset"""
    preset = None
    try:
        p = PermissionPreset.objects.get(id=presetid)
        p.delete()
        messages.success(request, f"Preset {p.name} erfolgreich gelöscht.")
    except PermissionPreset.DoesNotExist:
        messages.error(request, "Das angeforderte Preset existiert nicht.")
        return redirect('rights_edit')
    except Exception as e:
        messages.add_message(request, messages.ERROR, e)
        return redirect('rights_edit')

    return redirect('rights_edit')


@login_required(login_url='login')
@allowed_users(allowed_roles=['Schreiben - Nutzer'], url='user')
def user_delete(request, userid):
    """Delete a user"""
    user = None
    try:
        u = User.objects.get(id=userid)
        u.delete()
        messages.success(request, f"Nutzer {u.username} erfolgreich gelöscht.")
    except User.DoesNotExist:
        messages.error(request, "Der angeforderte Nutzer existiert nicht.")
        return redirect('user')
    except Exception as e:
        messages.add_message(request, messages.ERROR, e)
        return redirect('user')

    return redirect('user')


@login_required(login_url='login')
def profile(request):
    """Show user profile"""
    current_user = request.user
    if request.method == 'POST':
        form = forms.ProfileForm(request.POST, instance=current_user)
        if form.is_valid():
            user = form.save()

            messages.success(request, f"Nutzer {user.username} erfolgreich geändert.")
            return redirect('home')
    else:
        form = forms.ProfileForm(instance=current_user)

    context = {
        'form': form,
        'main_title': f"Nutzer {current_user.username} bearbeiten",
        'page_buttons': [["Passwort ändern", 'profile_password', 'icons/key-fill.svg']],
    }

    return render(request, 'accounts/user_form.html', context)


@login_required(login_url='login')
def profile_password(request):
    """Changing own user password"""
    current_user = request.user
    if request.method == 'POST':

templates/accounts/login.html
{% extends 'base/base.html' %}

{% block content %}
    <form method="POST" onsubmit="return (typeof submitted == 'undefined') ? (submitted = true) : !submitted">
        <div class="content_container card form_container">
            {% csrf_token %}
{#            {% for message in messages %}#}
{#                <div class="alert alert-danger" style="color: red">{{ message }}</div>#}
{#            {% endfor %}#}
            <h1 class="h3 mb-3 font-weight-normal">{{ sub_text|default:'Um auf diese Seite zugreifen zu können müssen sie sich einloggen.' }}</h1>
            <div class="content_container card form_container input_field">
                <label for="id_username">Nutzername</label>
                <input type="text" value="{{ last_username }}" name="username" id="inputName" class="form-control"
                       required autofocus>
            </div>
            <div class="content_container card form_container input_field">
                <label for="id_password">Passwort</label>
                <input type="password" name="password" id="inputPassword" class="form-control" required>
            </div>

        </div>
        <button type="submit">
            Login
        </button>
    </form>
{% endblock %}

templates/accounts/loginForm.html
<form action="{% url 'login' %}" id="dropdownUser" class="dropdownLogin-form" method="POST">
    {% csrf_token %}
    <label for="id_username">Nutzername</label><br>
    <input type="text" name="username" id="inputName" class="form-control" placeholder="Nutzername" required autofocus><br>
    <label for="id_password">Passwort</label><br>
    <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Passwort" required><br>
    <input type="hidden" name="next" value="{{ request.path }}">
    <button type="submit" class="btn btn-sucess">
        Login
    </button>
</form>

templates/accounts/user_form.html
{% extends "base/base.html" %}

{% block page_buttons %}
    {% include 'modal/delete.html' %}
    <button type="submit" id="confirm_deletion" value="" style="display:none"
            onclick="getUrl(this); customConfirm(this, 'Preset wirklich löschen?', 'Löschen')">{% include 'icons/delete.svg' %} Löschen
    </button>
{% endblock %}
{% block content %}
    <script>
        $(document).ready(function () {
            $('#id_preset').select2({ width: '100%'});
        });
    </script>
    <form method="POST" onsubmit="return (typeof submitted == 'undefined') ? (submitted = true) : !submitted">
        <div class="content_container card form_container">
            {% csrf_token %}
            {% for field in form.visible_fields %}
                <div class="content_container card form_container input_field" id="{{ field.name }}">
                    {{ field.label_tag }}<br/>
                    {{ field }}<br/>
                    {% if field.errors %}
                        <div class="alert alert-danger">
                            <strong>{{ field.errors|escape }}</strong>
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
        <button type="submit">{% include 'icons/ic_publish_24px.svg' %} Speichern</button>
    </form>
{% endblock %}

{% block javascripts %}
    {# load javascript if passed by context view #}
    {% if color_data %}
        {{ color_data|json_script:"color_data" }}
        <script>
            /**
             * Builds a JSON compatible List of all colors from the database, used to style
             * the select2 options
             * @returns {*[]} the JSON compatible list of entries
             */
            function buildColorList() {
                let color_data = JSON.parse(document.getElementById('color_data').textContent);
                let data = [color_data.length];
                for (let i = 0; i < color_data.length; i++) {
                    data[i] = {
                        id: color_data[i][0],
                        text: color_data[i][1],
                        html: color_data[i][2],
                    };
                }
                return data;
            }

            $(document).ready(function () {
                var data = buildColorList();

                $('.color_select').select2({
                    width: '100%',
                    data: data,
                    escapeMarkup: function (markup) {
                        return markup;
                    },
                    templateResult: function (data) {
                        return data.html;
                    },
                    templateSelection: function (data) {
                        return data.html;
                    }
                })
            });
        </script>
    {% endif %}
    {% if js_script %}
        {% if initial %}
            {{ initial|json_script:"initial" }}
            <script type="text/javascript">
                window.onload = function () {
                    let current = document.getElementById('id_groups').value;
                    if (current != '') {
                        current = JSON.parse(current);
                        current.forEach(e => addDependencies(e));
                    } else {
                        const initial = JSON.parse(document.getElementById('initial').textContent);
                        let encoded = []
                        for (let i = 0; i < initial.length; i++) {
                            encoded.push({
                                "value": initial[i].id,
                                "name": initial[i].name,
                                "clean_name": escapeUserHtml(initial[i].name),
                                "write": getWriteToken(initial[i].name)
                            });
                        }
                        encoded.forEach(e => perm.addTags([e]));
                    }
                };
            </script>
        {% endif %}
        {% include "js/select_permission_presets_js.html" %}
    {% endif %}
{% endblock %}

templates/accounts/user_list.html
{% extends "base/base.html" %}
{% load user_tags %}

{% block content %}
    {% include 'modal/delete.html' %}
    {% if user_list|length > 0 %}
        <table class="alternating_list">
            <thead>
                <th scope="col">Name</th>
                <th scope="col">E-Mail</th>
                <th scope="col">Rolle</th>
                <th scope="col">Aktionen</th>
            </thead>
            <tbody>
            {% for u in user_list %}
                <tr>
                    <td data-label="Name">
                        <div class="user_color">
                            <div class="user_color_circle" style="background-color: {{ u.get_color }}"></div>
                            {{ u.username }}
                        </div>
                    </td>
                    <td data-label="E-Mail">{{ u.email }}</td>
                    <td data-label="Rolle">{{ u.preset|default:"<i>Benutzerdefiniert</i>" }}</td>
                    <td data-label="Aktionen">
                        {% if buttons %}
                            <div>
                                {% for button in buttons %}
                                    {% if button.2 == 'user_delete' %}
                                        <button id="confirm_deletion" value="{% url button.2 u.id %}"
                                                class="{{ button.1 }} underline_button"
                                                onclick="customConfirm(this, 'Nutzer {{ u.username }} wirklich löschen?', 'Löschen')">
                                            {% if button|length > 3 %}
                                                {% include button.3 %}{% endif %}{{ button.0 }}
                                        </button>
                                    {% else %}
                                        <a id="{{ button.2 }}" href="{% url button.2 u.id %}" class="{{ button.1 }} underline_button">
                                            {% if button|length > 3 %}
                                                {% include button.3 %}{% endif %}{{ button.0 }}</a>
                                    {% endif %}

                                {% endfor %}
                            </div>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}
{% endblock %}