datenbank_physik/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('label/', include('labels.urls')),
    path('', include('public.urls')),
    path('inventory/', include('inventory.urls')),
    path('experiment/', include('experiment_list.urls')),
    path('device/', include('devices.urls')),
    path('bookings/', include('bookings.urls')),
    path('commits/', include('commits.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'datenbank_physik.views.custom_page_not_found'
handler500 = 'datenbank_physik.views.custom_server_error'

devices/urls.py
from django.urls import path, re_path

from . import views

urlpatterns = [
    path('', views.devices_overview, name="devices"),

    path('add/', views.DeviceDocumentCreate.as_view(), name='device_add'),
    path('<int:device_id>/', views.custom_redirect),
    path('<int:pk>/edit/', views.DeviceDocumentUpdate.as_view(), name='device-update'),
    path('<int:pk>/delete/', views.DeviceDelete.as_view(), name='device-delete'),
    path('<int:device_id>/description/', views.device_fullpage, name="device_description"),
    path('<int:device_id>/inventory/', views.device_fullpage, name="device_view"),
    path('<int:device_id>/previous/', views.get_previous_device),
    path('<int:device_id>/next/', views.get_next_device),
    path('<int:device_id>/<str:_>/', views.device_fullpage, name="device_fullpage"),

    path('category/create/', views.location_create, name="location_create"),
    re_path(r'^category/create/(?P<categoryid>\d+)/$', views.location_create, name="location_create_sub"),
    path('category/<int:_>/', views.devices_overview),
    path('category/<int:locationid>/edit/', views.location_edit, name="location_edit"),
    path('category/<int:locationid>/delete/', views.location_delete, name="location_delete"),
]

labels/urls.py
from django.urls import path, re_path

from . import views

urlpatterns = [
    path('', views.label_showAll, name="label"),
    path('create/', views.label_create, name="label_create"),
    re_path(r'^(?P<labelid>\d+)/edit/$', views.label_edit, name="label_edit"),
    re_path(r'^(?P<labelid>\d+)/delete/$', views.label_delete, name="label_delete"),

    path('color/', views.label_color, name="color_edit"),
    re_path(r'^color/(?P<colorid>\d+)/delete/$', views.color_delete, name="color_delete"),

    re_path(r'^(?P<labelid>\d+)/view/$', views.label_view, name="label_view"),
]

devices/models.py
from django.db import models

# Create your models here.

devices/forms.py
import json

import django.utils
from django import forms
from django.forms import ModelForm, inlineformset_factory

from public.models import Device, Commit, Label, Document, Location
from .utilities import get_locations
from .utils import get_device_labels, similar_commits


class CreateLocationForm(ModelForm):
    """Form for creating a new location"""
    name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'placeholder': "Name des Standorts..."
            }
        ),
        label="Name",
    )

    token = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'placeholder': "Kürzel des Standorts..."
            }
        ),
        label="Kürzel",
    )

    parent = forms.ChoiceField(
        choices=[],
        label="Überstandort",
        required=False,
    )

    class Meta:
        model = Location
        fields = ('name', 'token')

    def clean_name(self):
        """Checks if location with identical name and parent already exists, denies creation if so"""
        name = self.cleaned_data.get('name')
        parent = self.data.get('parent')
        instance = self.instance
        try:
            if parent != '':
                match = Location.objects.get(name=name, parent=parent)
            else:
                match = Location.objects.get(name=name, parent__isnull=True)
            if (instance is not None) and (match == instance):
                return name
        except Location.DoesNotExist:
            # Unable to find a location, this is fine
            return name

        # Location with this name and parent was found, raise an error
        raise forms.ValidationError("Dieser Standort mit diesem Überstandort existiert bereits.")


class EditLocationForm(ModelForm):
    """Form for editing an existing location"""
    name = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'placeholder': "Name des Standorts..."
            }
        ),
        label="Name",
    )

    token = forms.CharField(
        widget=forms.TextInput(
            attrs={
                'placeholder': "Kürzel des Standorts..."
            }
        ),
        label="Kürzel",
    )

    parent = forms.ChoiceField(
        widget=forms.Select(),
        choices=[],
        label="Überstandort",
        required=False,
    )

    device = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'class': "device_select",
                'id': "device_id",
                'placeholder': "Geräte auswählen..."
            }
        ),
        label="Geräte",
        required=False,
    )

    class Meta:
        model = Location
        fields = ('name', 'token',)

    def clean_name(self):
        """Checks if location with identical name and parent already exists, denies change if so"""
        name = self.cleaned_data.get('name')
        parent = self.data.get('parent')
        instance = self.instance
        try:
            if parent != '':
                match = Location.objects.get(name=name, parent=parent)
            else:
                match = Location.objects.get(name=name, parent__isnull=True)
            if (instance is not None) and (match == instance):
                return name
        except Location.DoesNotExist:
            # Unable to find a location, this is fine
            return name

        # Location with this name and parent was found, raise an error
        raise forms.ValidationError("Dieser Standort mit diesem Überstandort existiert bereits.")


class DeviceForm(forms.ModelForm):
    class Meta:
        model = Device
        name = "device"
        # fields = '__all__'
        fields = (
            'name', 'description', 'ordernumber', 'inventorynumber', 'ifpcode', 'comment', 'supplier', 'amount',
            'location', 'tags')

    def __init__(self, *args, **kwargs):
        # to delete colon after field's name
        # kwargs.setdefault('label_suffix', '')
        super(DeviceForm, self).__init__(*args, **kwargs)
        self.fields["location_list"].choices = get_locations(Location.objects.filter(depth=2), 2)
        if self.instance and self.instance.id is not None:
            self.fields["labels"].initial = get_device_labels(self.instance)

    def save(self, create_commits=False, user=None, commit=False):
        # if self.instance.id is None than the device is being created now
        # if creating a device confirmed_By is always None
        created = self.instance.id is None

        if create_commits:
            # TODO put the code below in another function
            # TODO to fill
            if created:
                device = super(DeviceForm, self).save(commit=True)
                commit = Commit(device=device,
                                field="!create",
                                timestamp=django.utils.timezone.now(),
                                old_data="",
                                new_data="",
                                author=user,
                                confirmed_by=None,
                                confirmed_at=None,
                                status="auto_approved")
                commit.save()
            else:
                model = Device.objects.get(id=self.instance.id)
                for changed_element in self.changed_data:
                    if changed_element == "location_list":
                        continue
                    attr = getattr(model, changed_element)
                    old_data = attr if attr else ""
                    if changed_element == "tags":  # we get a list of dictionaries from tagify for the tags, we only want a list
                        old_data = json.dumps(sorted([e["value"] for e in json.loads(old_data)])) if attr else '[]'
                        new_data = '[]' if self.data[changed_element] == "" else json.dumps(sorted([e["value"] for e in json.loads(self.data[changed_element])]))
                    elif changed_element == "location":  # here we want to save the id for later reference, not the name
                        old_data = old_data.id if old_data else ""
                        new_data = self.cleaned_data[changed_element].id
                    elif bool(changed_element) and changed_element == "labels":
                        old_data = json.dumps(sorted([str(e.id) for e in Label.objects.filter(device=model)])) if attr else '[]'  # here we need a list of all label ids for our device
                        new_data = '[]' if self.data[changed_element] == "" else json.dumps(sorted([e["value"] for e in json.loads(self.data[changed_element])]))  # we get a list of dictionaries from tagify
                    else:  # default case: Just save whatever data is being handed over
                        old_data = old_data
                        new_data = self.cleaned_data[changed_element]

                    if similar_commits(old_data, new_data):
                        continue
                    if changed_element in ["name", "!delete", "description", "comment"]:
                        status = "not_handled"
                    else:
                        status = "auto_approved"

                    commit = Commit(device=model,
                                    field=changed_element,
                                    timestamp=django.utils.timezone.now(),
                                    old_data=old_data,
                                    new_data=new_data,
                                    author=user,
                                    confirmed_by=None,
                                    confirmed_at=None,
                                    status=status)
                    commit.save()
        device = super(DeviceForm, self).save(commit=True)

        if not created and create_commits:
            device.name = self.initial["name"]
            device.description = self.initial["description"]
            device.comment = self.initial["comment"]
        device.save()

        return device

    def __str__(self):
        return "device"

    name = forms.CharField(
        label="Name",
        widget=forms.TextInput(
            attrs={'id': 'device_name',
                   'placeholder': 'Gerätename...'}
        )
    )
    location = forms.ModelChoiceField(
        queryset=Location.objects.filter(depth=2),
        required=False,
        widget=forms.Select(
            attrs={'id': 'device_location',
                   'style': 'display: none'
                   }
        )
    )

    location_list = forms.ChoiceField(
        label="Standort",
        required=True,
        widget=forms.Select(
            attrs={'id': 'device_location_list',

                   }
        )
    )

    description = forms.CharField(
        label="Info",
        required=False,
        widget=forms.Textarea(

            attrs={'id': 'device_description',
                   'name': 'device[description]',
                   'cols': 0,
                   'rows': 5,
                   'placeholder': 'Geräteinformation...'
                   }
        )
    )
    tags = forms.CharField(
        label="Schlagworte",
        required=False,
        widget=forms.TextInput(
            attrs={'name': 'tag',
                   'placeholder': 'Schlagworte zur Suche...'
                   }
        ),
    )
    ordernumber = forms.CharField(
        label="Bestellnummer",
        required=False,
        widget=forms.TextInput(
            attrs={'id': 'device_ordernumber',
                   'placeholder': 'Bestellnummer...'}
        )
    )
    inventorynumber = forms.IntegerField(
        label="Inventarnummer",
        required=False,
        widget=forms.NumberInput(
            attrs={'id': 'device_inventorynumber',
                   'placeholder': 'Inventarnummer...'}
        )
    )
    ifpcode = forms.CharField(
        label="IFP-Code",
        required=False,
        widget=forms.TextInput(

templates/forms/bbcode_preview.html
{{ content|bbcode|safe }}

templates/forms/category.html
{% extends "base/base.html" %}
{% load custom_tags %}

{% block page_buttons %}
    <script>
        $(document).ready(function () {
            $('#id_parent').select2({ width: '100%'});
        });
    </script>
    {% if id %}
        {% include 'modal/delete.html' %}
        <button id="confirm_deletion"
                type="submit"
                value="{% url delete_url id %}"
                onclick="customConfirm(this, 'Kategorie wirklich löschen?', 'Löschen',
                'Das Löschen der Kategorie muss durch eine Änderung bestätigt werden.')"
                {% if form.instance|pending_delete %}disabled{% endif %}>{% include 'icons/delete.svg' %} Löschen
        </button>
    {% endif %}
{% endblock %}
{% block content %}
    <form method="POST" onsubmit="return (typeof submitted == 'undefined') ? (submitted = true) : !submitted">
        <div class="content_container card form_container">
            {% csrf_token %}
            {% for field in form.visible_fields %}
                <div class="content_container card form_container input_field" id="{{ field.name }}">
                    {{ field.label_tag }}<br/>
                    {{ field }}<br/>
                    {% if field.errors %}
                        <div class="alert alert-danger">
                            <strong>{{ field.errors|escape }}</strong>
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
        <button type="submit">{% include 'icons/ic_publish_24px.svg' %} Speichern</button>
    </form>
{% endblock %}

{% block javascripts %}
    {% if device_list %}
        {{ device_list|json_script:"device_list" }}
        <script>
            const device_list = JSON.parse(document.getElementById('device_list').textContent);
            var input = document.querySelector('textarea[name=device]')
            var dev = new Tagify(input, {
                whitelist: device_list.map(({id, name}) => ({value: id, name: name, clean_name: escapeUserHtml(name),})),
                enforceWhitelist: true,
                tagTextProp: 'clean_name',
                editTags: false,
                dropdown: {
                    placeAbove: false,
                    enabled: 0,
                    mapValueTo: 'name',
                    highlightFirst: true,
                    searchKeys: ['name'],
                    maxItems: 50,
                },
            })
        </script>
    {% endif %}
    {% if experiment_list %}
        {{ experiment_list|json_script:"experiment_list" }}
        <script>
            const experiment_list = JSON.parse(document.getElementById('experiment_list').textContent);
            var input = document.querySelector('textarea[name=experiment]')
            var exp = new Tagify(input, {
                whitelist: experiment_list.map(({id, name}) => ({value: id, name: name, clean_name: escapeUserHtml(name), style: paintExp(name)})),
                enforceWhitelist: true,
                tagTextProp: 'clean_name',
                editTags: false,
                dropdown: {
                    placeAbove: false,
                    enabled: 0,
                    mapValueTo: 'name',
                    highlightFirst: true,
                    searchKeys: ['name'],
                    maxItems: 50,
                },
            })
        </script>
    {% endif %}
{% endblock %}

templates/forms/color.html
{% extends "base/base.html" %}
{% block page_buttons %}
        {% include 'modal/delete.html' %}
        <button type="submit" id="confirm_deletion" value="" style="display:none"
                onclick="getUrl(this, '{{ type }}'); customConfirm(this, 'Farbe wirklich löschen?', 'Löschen')">{% include 'icons/delete.svg' %} Löschen
        </button>
{% endblock %}
{% block content %}
    <script>
        $(document).ready(function () {
            $('#select_id').select2({ width: '100%'});
        });
    </script>
    <form method="POST" id="color_form" onsubmit="return (typeof submitted == 'undefined') ? (submitted = true) : !submitted">
        <div class="content_container card form_container">
            {% csrf_token %}
            {% for field in form.visible_fields %}
                <div class="content_container card form_container input_field" id="{{ field.name }}">
                    {{ field.label_tag }}<br/>
                    {{ field }}<br/>
                    {% if field.errors %}
                        <div class="alert alert-danger">
                            <strong>{{ field.errors|escape }}</strong>
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
        </div>
        <button type="submit">{% include 'icons/ic_publish_24px.svg' %} Speichern</button>
    </form>
    {% include "js/color_form_js.html" %}
{% endblock %}

templates/forms/default.html
{% extends "base/base.html" %}

{% block content %}
    <form method="POST">
        <div class="content_container card form_container">
            {% csrf_token %}
            {% for field in form.visible_fields %}
                {{ field.label_tag }}
                {{ field }}
            {% endfor %}
            {% include 'modal/delete.html' %}
            <button type="button" id="confirm_deletion" name="delete_btn" style="display: none" value="" onclick="confirmDeletion(this)">
                 Delete
             </button>
        </div>

        <div class="inline_container content_container" style="justify-content: right">
            <input type="hidden" name="next" value="{{ request.path }}"/>
            <button type="submit">{% include 'icons/ic_publish_24px.svg' %} Speichern</button>
        </div>
        {% if form.errors %}
                <ul>
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger" >
                            <strong>{{ error }}</strong>
                        </div>
                        </br>
                    {% endfor %}
                {% endfor %}
                </ul>
            {% endif %}
    </form>
{% endblock %}

{% block javascripts %}
    {# load javascript if passed by context view #}
    {% if js_script %}
        <script type="text/javascript">{% include js_script %}</script>
    {% endif %}
{% endblock %}

templates/forms/device.html
{% extends 'base/base.html' %}
{% load define_action %}
{% load user_tags %}

{% block page_buttons %}
    {% if pk %}
        <a href="{% url 'device_description' pk %}" style="margin-right: 1em;">Zurück zum Gerät (Änderungen werden nicht übernommen)</a>
        {% include 'modal/delete.html' %}
        <button type="submit" id="confirm_deletion" value="{% url 'device-delete' pk %}"
                onclick="customConfirm(this, 'Gerät wirklich löschen?', 'Löschen', 'Das Löschen des Geräts muss durch eine Änderung bestätigt werden.')" xmlns="http://www.w3.org/1999/html">
            {% include 'icons/delete.svg' %} Löschen
        </button>
    {% endif %}
{% endblock %}

{% block content %}
<div class="content_container card form_container">
    <form id=device_form method="post" enctype="multipart/form-data" name="device" onsubmit="return (typeof submitted == 'undefined') ? (submitted = true) : !submitted">
        {% csrf_token %}
        <div class="bookings_main">Informationen</div>
        <div class="content_container card form_container input_field_bookings">
            {% for hidden in form.hidden_fields %}
            {{hiddden}}
            {%endfor%}
            <div class="bookings_categories">
                {{ form.name.label_tag }}
            </div>
            {{ form.name }}<br/>
            <div class="bookings_categories">
                {{ form.description.label_tag }}
            </div>
            <div class="comment_container_bookings">
                {% include 'forms/editor.html' with class="comment" txt=form.description id=form.description.id_for_label%}<br/>
            </div><br>
            <div class="bookings_categories">
                {{ form.comment.label_tag }}
            </div>
            <div class="comment_container_bookings">
                {% include 'forms/editor.html' with class="comment" txt=form.comment id=form.comment.id_for_label%}<br/>
            </div><br>
            <div class="bookings_categories">
                {{ form.inventorynumber.label_tag }}
            </div>
            {{ form.inventorynumber }}<br/>
            <div class="bookings_categories">
                {{ form.ordernumber.label_tag }}
            </div>
            {{ form.ordernumber }}<br/>
            <div class="bookings_categories">
                {{ form.supplier.label_tag }}
            </div>
            {{ form.supplier }}<br/>
            <div class="bookings_categories">
                {{ form.ifpcode.label_tag }}
            </div>
            {{ form.ifpcode }}<br/>
            <div class="bookings_categories">
                {{ form.tags.label_tag }}
            </div>
            {{ form.tags}}<br/>
            <div class="bookings_categories">
                {{ form.labels.label_tag }}
            </div>
            {{ form.labels }}<br/>
            {% include 'js/experiment_label_select.html' with device_list="[]" %}

        </div>
        <div class="bookings_main">Verfügbarkeit</div>
        <div class="content_container card form_container input_field_bookings">
            <div class="bookings_categories">
                {{ form.amount.label_tag }}
            </div>
            {{ form.amount }}<br/>
        </div>
        <div class="content_container card form_container input_field_bookings">
            <div class="bookings_categories">Standort:</div>
            {{ form.location }}
            {{ form.location_list }}<br/>
        </div>
        <hr>
        {% include 'forms/documentFormSet.html' with device=form user=user %}
        <hr>
        <script>

        $(document).ready(function () {
            $('#device_location_list').select2({ width: '100%', placeholder: "Standort auswählen...",
                allowClear: true,});
        });

        $(document).ready(function () {
            if ($('#device_location_list').val() === null){
                $('#submit_button').prop('disabled', true);
                $('#location_check').css('display', 'flex');
            }
            else{
                $('#submit_button').prop('disabled', false);
                $('#location_check').css('display', 'none');
            }
         });

        $('#device_location_list, #device_amount').change(function () {
            if ($('#device_location_list').val() === null && $('#device_amount').val() === null) {
                $('#submit_button').prop('disabled', true);
                $('#location_check').css('display', 'flex');
                $('#device_amount_check').css('display', 'flex');
            }
            if ($('#device_location_list').val() !== null && $('#device_amount').val() !== null) {
                $('#submit_button').prop('disabled', false);
                $('#location_check').css('display', 'none');
                $('#device_amount_check').css('display', 'none');
            }
            if ($('#device_location_list').val() === null) {
                $('#location_check').css('display', 'flex');
                $('#submit_button').prop('disabled', true);
            }else{
                $('#location_check').css('display', 'none');
            }
            if ($('#device_amount').val() === null || $('#device_amount').val() === ""){
                $('#device_amount_check').css('display', 'flex');
                $('#submit_button').prop('disabled', true);
            }else{
                $('#device_amount_check').css('display', 'none');
            }
        });

        // input choice value
            let standort = $("#device_location").val();
            $("#device_location_list").val(standort);
        function putLocation(){
             let location_list = $("#device_location_list").val();
            $("#device_location").val(location_list);
        }
        //this function disables first option in document security_level
        //so first choice can be a placeholder
        function disable_first_choice(){
            $('option[value=""]').attr("disabled", "disabled");
            //disable private choice depends on user right
            //if it has vla rights
            {% if not user|has_group:"Sicherheitsstufe - TU Darmstadt" %}
                $('option:contains("TU Darmstadt")').hide();
            {%endif%}
            // if it hs tu darmstadt rights
            {% if not user|has_group:"Sicherheitsstufe - VLA" %}
                $('option:contains("VLA")').hide();
            {%endif%}
        }
        disable_first_choice();

        //create tags
        var input = document.querySelector('input[name=tags]');
        new Tagify(input);

        </script>

        <div style="display: flex; justify-content: center; align-items: center;">
        <button id="submit_button" type="submit" onclick="putLocation()" style="float: left; margin-right: auto;">{% include 'icons/ic_publish_24px.svg' %} Speichern</button>
        <div id="device_amount_check" class="message_container alert-danger" style="display: None; min-height:2.5em; padding: 0 1em; margin-left: 2em; margin-bottom: 0.5em;">Das Feld Anzahl muss ausgefüllt werden!</div>
        <div id="location_check" class="message_container alert-danger" style="display: None; min-height:2.5em; padding: 0 1em; margin-left: 2em; margin-bottom: 0.5em;">Es muss ein Standort ausgewählt werden!</div>
        </div>

        <script>
            //if there is unhandled commits disable submit and delete button
        $('#submit_button').attr('disabled', {{ submit_button|default_if_none:"false" }});
        $('#confirm_deletion').attr('disabled', {{ submit_button|default_if_none:"false" }});

        </script>
    </form>
</div>
{% endblock %}

templates/forms/documentForm.html
{% load define_action %}
{% load static %}
{# if there is already a formset form is true #}
{% if form %}
{% set True as formSet %}
{%else%}
{% set '__name__' as index %}
{% getDocForm as form %}
{%endif%}

<div class='card file widthy' id='device_documents_{{ index }}'>
    {% if formSet %}
    {% for hidden in form.hidden_fields %}
    {{ hidden }}
    {% endfor %}
    {%else%}
    <input type='hidden' name='document_set-{{ index }}-device' value='{{device.instance.id}}'
           id='id_document_set-{{ index }}-device'>
    <input type='hidden' name='document_set-{{ index }}-id' value=''
           id='id_document_set-{{ index }}-id'>

    {%endif%}

    <header style='height: 32px'>
        <label for='id_document_set-{{index}}-marked' class='check_container'>
            {{form.marked}}
            {% include 'icons/preview_picture.svg' %}
        </label>


        <h2>{{form.instance.name|default_if_none:""}}</h2>
        <input type='hidden' name='document_set-{{ index }}-DELETE' id='id_document_set-{{ index }}-DELETE' value=''>
        <button type='button' class='document_delete delete' onclick="hideDeleteOn('device_documents_{{ index }}', '{{ index }}' );">
            {% include 'icons/delete.svg' %}
        </button>
    </header>
    <script>
        //TODO add images to DeviceDocument Form
        // if there is a form i should just display its image --> DONE
        // if there is not than i should enable uploading an image
        // i should display he uploaded image in the website
        // i should change the title using jquery i guess?
        // i should manage saving it in backend with python



    </script>
    {{form.image}}
    <div class='image_and_comment'>
        {#if there is an image or not #}
        {% if form.instance.image_name %}

        <a class='image' href="{{ MEDIA_URL }}{{form.instance.image_name}}"
           style="background-image: url('{{ MEDIA_URL }}{{form.instance.image_name}}')">
        </a>
        {%else%}
        <div id="FI{{ index }}" class="image"></div>
        {%endif%}
        {{ form.position}}

        <label>
            {{form.comment}}
        </label>
        {{form.image_name}}
        {{form.image_size}}
        {{form.private}}

    </div>

</div>

templates/forms/documentFormExperiment.html
{% load define_action %}
{% load static %}
{# if there is already a formset form is true #}
{% if form %}
{% set True as formSet %}
{%else%}
{% set '__name__' as index %}
{% getDocFormExp as form %}
{%endif%}

<div class='card file widthy' id='experiment_documents_{{ index }}'>
    {% if formSet %}
    {% for hidden in form.hidden_fields %}
    {{ hidden }}
    {% endfor %}
    {%else%}
    <input type='hidden' name='document_set-{{ index }}-experiment' value='{{experiment.instance.id}}'
           id='id_document_set-{{ index }}-experiment'>
    <input type='hidden' name='document_set-{{ index }}-id' value=''
           id='id_document_set-{{ index }}-id'>
    {%endif%}

    <header style='height: 32px'>
        <label for='id_document_set-{{index}}-marked' class='check_container'>
            {{form.marked}}
            {% include 'icons/preview_picture.svg' %}
        </label>


        <h2>{{form.instance.name|default_if_none:""}}</h2>
        <input type='hidden' name='document_set-{{ index }}-DELETE' id='id_document_set-{{ index }}-DELETE' value=''>
        <button type='button' class='document_delete delete' onclick="hideDeleteOn('experiment_documents_{{ index }}', '{{ index }}' );">
            {% include 'icons/delete.svg' %}
        </button>
    </header>
    <script>
        //TODO add images to DeviceDocument Form
        // if there is a form i should just display its image --> DONE
        // if there is not than i should enable uploading an image
        // i should display he uploaded image in the website
        // i should change the title using jquery i guess?
        // i should manage saving it in backend with python



    </script>
    {{form.image}}
    <div class='image_and_comment'>
        {#if there is an image or not #}
        {% if form.instance.image_name %}

        <a class='image' href="{{ MEDIA_URL }}{{form.instance.image_name}}"
           style="background-image: url('{{ MEDIA_URL }}{{form.instance.image_name}}')">
        </a>
        {%else%}
        <div id="FI{{ index }}" class="image"></div>
        {%endif%}
        {{ form.position}}

        <label>
            {{form.comment}}
        </label>
        {{form.image_name}}
        {{form.image_size}}
        {{form.private}}

    </div>

</div>