datenbank_physik/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('label/', include('labels.urls')),
    path('', include('public.urls')),
    path('inventory/', include('inventory.urls')),
    path('experiment/', include('experiment_list.urls')),
    path('device/', include('devices.urls')),
    path('bookings/', include('bookings.urls')),
    path('commits/', include('commits.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'datenbank_physik.views.custom_page_not_found'
handler500 = 'datenbank_physik.views.custom_server_error'

inventory/urls.py
from django.urls import path, re_path

from . import views

urlpatterns = [
    path('', views.inventory_showAll, name="inventory"),
    path('create/', views.inventory_create, name="inventory_create"),
    re_path(r'^(?P<inventoryid>\d+)/view/$', views.inventory_view, name="inventory_view"),
    re_path(r'^(?P<inventoryid>\d+)/end/$', views.inventory_end, name="inventory_end"),
    re_path(r'^(?P<inventoryid>\d+)/delete/$', views.inventory_delete, name="inventory_delete"),
    path('<int:inventoryid>/remove/<int:deviceid>', views.inventory_remove_device, name="inventory_remove_device"),

    # AJAX
    path('change_device/', views.inventory_change_device, name="inventory_change_device"),
    path('fullpage/', views.fullpage_inventory, name="fullpage_inventory"),

    path('loan/', views.loan_showAll, name="loan"),
    path('loan/create/', views.loan_create, name="loan_create"),
    re_path(r'^loan/(?P<loanid>\d+)/return/$', views.loan_return, name="loan_return"),
    re_path(r'^loan/(?P<loanid>\d+)/view/$', views.loan_view, name="loan_view"),
    re_path(r'^loan/(?P<loanid>\d+)/delete/$', views.loan_delete, name="loan_delete"),
]

labels/urls.py
from django.urls import path, re_path

from . import views

urlpatterns = [
    path('', views.label_showAll, name="label"),
    path('create/', views.label_create, name="label_create"),
    re_path(r'^(?P<labelid>\d+)/edit/$', views.label_edit, name="label_edit"),
    re_path(r'^(?P<labelid>\d+)/delete/$', views.label_delete, name="label_delete"),

    path('color/', views.label_color, name="color_edit"),
    re_path(r'^color/(?P<colorid>\d+)/delete/$', views.color_delete, name="color_delete"),

    re_path(r'^(?P<labelid>\d+)/view/$', views.label_view, name="label_view"),
]

inventory/models.py
import os

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.core.cache import cache
from django.db import models
from django.db.models import signals
from django.dispatch import receiver
from django.http import request
from django.utils import timezone

from public.models import Device, Location, Document

User = get_user_model()


class Loan(models.Model):
    """DB model for loans"""
    startdate = models.DateTimeField(auto_now_add=True)
    enddate = models.DateTimeField(null=True, blank=True)
    loaned_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    loaned_to = models.CharField(max_length=255, blank=True, null=True)
    active = models.BooleanField(default=False)

    LOAN_CHOICES = (
        ('loan', "Verleih"),
        ('repair', "E-Werkstatt"),
    )
    type = models.CharField(max_length=255, choices=LOAN_CHOICES)
    comment = models.TextField(blank=True, null=True)
    info = models.FileField(upload_to='', blank=True, null=True)

    def __str__(self):
        return self.comment

    def delete(self, *args, **kwargs):
        if self.info:
            try:
                os.remove(os.path.join(settings.MEDIA_ROOT, self.info.name))
            except Exception as e:
                messages.add_message(request, messages.ERROR, e)

        super(Loan, self).delete(*args, **kwargs)

    def add_device(self, id, amount, comment):
        device = Device.objects.get(id=id)
        if self.type == 'loan':
            device.add_loan(amount)
        else:
            device.add_repair(amount)
        self.loanitem_set.add(LoanItem(item=device, amount=amount, comment=comment), bulk=False)


    def start(self, user):
        self.active = True
        self.loaned_by = user
        self.save()

    def end_loan(self):
        self.active = False
        for l in self.loanitem_set.all():
            if self.type == 'loan':
                l.item.remove_loan(l.amount)
            else:
                l.item.remove_repair(l.amount)
        self.enddate = timezone.now()
        self.save()

    def is_due(self):
        if self.type == 'loan':
            return self.enddate <= timezone.now()
        return False


class LoanItem(models.Model):
    """DB model for loan instances"""
    item = models.ForeignKey(Device, on_delete=models.CASCADE, null=True)
    amount = models.IntegerField()
    comment = models.CharField(max_length=255, blank=True, null=True)
    loan = models.ForeignKey(Loan, on_delete=models.CASCADE)

    def __str__(self):
        return self.item.name


class Inventory(models.Model):
    """DB model for inventories"""
    name = models.CharField(max_length=255, blank=True, null=True)
    startdate = models.DateTimeField(auto_now_add=True)
    enddate = models.DateTimeField(null=True, blank=True)
    active = models.BooleanField(default=False)
    started_by = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        """Returns inventory name as a string"""
        return self.name

    def start(self, user):
        """Starting an inventory"""
        self.active = True
        self.started_by = user
        self.save()

    def end(self):
        """Ending an inventory"""
        self.active = False
        self.enddate = timezone.now()
        self.save()

    def add(self, device):
        """Adding a device to an active inventory"""
        item = self.inventoryitem_set.filter(item=device)
        if not item.exists():
            self.inventoryitem_set.add(InventoryItem(item=device), bulk=False)

    def remove(self, device):
        """Removing a device from an active inventory"""
        items = self.inventoryitem_set.filter(item=device).delete()

    def has_device(self, device):
        """Returns true if the device is catalogued in this inventory"""
        if self.inventoryitem_set.filter(item=device.id):
            return True
        else:
            return False

    def clear(self):
        """Removes all catalogued devices from this inventory"""
        self.inventoryitem_set.all().delete()


class InventoryItem(models.Model):
    """DB model for an inventory instance"""
    item = models.ForeignKey(Device, on_delete=models.CASCADE, null=True)
    info = models.TextField(blank=True, null=True)
    inventory = models.ForeignKey(Inventory, on_delete=models.CASCADE)

    def __str__(self):
        """Returns device name as a string"""
        return self.item.name

inventory/views.py
import json
import locale

from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404, HttpResponse
from django.shortcuts import render
from django.template.loader import render_to_string

from accounts.decorators import *
from devices.views import get_administration
from . import forms
from .models import *
from .utilities import *

locale.setlocale(locale.LC_TIME, locale.normalize(''))
User = get_user_model()


@login_required(login_url='login')
@allowed_users(allowed_roles=['Lesen - Inventur'], url='devices')
def inventory_showAll(request):
    """Shows the active and all completed inventories"""
    current_user = request.user
    active_inventories = Inventory.objects.filter(active=True)
    inactive_inventories = Inventory.objects.filter(active=False)

    active_buttons = [["Anzeigen", 'blue', 'inventory_view', 'icons/ic_eye_24px.svg']]
    inactive_buttons = [["Anzeigen", 'blue', 'inventory_view', 'icons/ic_eye_24px.svg']]

    if current_user.hasGroup("Schreiben - Inventur"):
        active_buttons.append(["Beenden", 'green', 'inventory_end', 'icons/x.svg'])
        inactive_buttons.append(["Löschen", 'red', 'inventory_delete', 'icons/x.svg'])

    if active_inventories:
        messages.warning(request, "Es kann immer nur eine Inventur aktiv sein.")

    context = {
        'active_inventories': active_inventories,
        'inactive_inventories': inactive_inventories,
        'main_title': "Inventur",
        'active_buttons': active_buttons,
        'inactive_buttons': inactive_buttons,
        'already_active': get_activeInventory(),
    }

    return render(request, 'inventory/overview/inventory_list.html', context)


@login_required(login_url='login')
@allowed_users(allowed_roles=['Schreiben - Inventur'], url='inventory')
def inventory_create(request):
    """Creating a new inventory"""
    if get_activeInventory() is None:
        current_user = User.objects.get(id=request.user.id)

        form = forms.CreateInventoryForm()
        if request.method == 'POST':
            form = forms.CreateInventoryForm(request.POST)
            if form.is_valid():
                inventory = form.save()
                inventory.start(current_user)
                name = inventory.name if inventory.name is not None else ""
                messages.success(request, f"Inventur {name} gestartet.")

                return redirect('inventory')

        context = {
            'form': form,
        }

        return render(request, 'forms/default.html', context)
    else:
        return redirect('inventory')


@login_required(login_url='login')
@allowed_users(allowed_roles=['Lesen - Inventur'], url='devices')
def inventory_view(request, inventoryid):
    """Detailed view of one inventory"""
    try:
        current_inventory = Inventory.objects.get(id=inventoryid)
    except ObjectDoesNotExist as e:
        raise Http404

    hits = current_inventory.inventoryitem_set.values_list('item', flat=True).distinct()
    hits = Device.objects.filter(id__in=hits)
    misses = Device.objects.all().exclude(id__in=hits)

    context = {
        'inventory': current_inventory,
        'misses': misses,
        'main_title': f"Inventur vom {current_inventory.startdate.strftime('%d.%m.%Y')}",
        'page_buttons': [["Übersicht - Inventur", 'inventory']],
    }

    return render(request, 'inventory/inventory.html', context)


@login_required(login_url='login')
@allowed_users(allowed_roles=['Schreiben - Inventur'], url='inventory')
def inventory_end(request, inventoryid):
    """Ending an active inventory"""
    try:
        i = Inventory.objects.get(id=inventoryid)
        name = i.name if i.name is not None else ""
        i.end()
        messages.success(request, f"Inventur {name} erfolgreich beendet.")
    except Inventory.DoesNotExist:
        messages.error(request, "Die angeforderte Inventur existiert nicht.")
        return redirect('inventory')
    except Exception as e:
        messages.add_message(request, messages.ERROR, e)
        return redirect('inventory')

    return redirect('inventory')


@login_required(login_url='login')
@allowed_users(allowed_roles=['Schreiben - Inventur'], url='inventory')
def inventory_delete(request, inventoryid):
    """Deleting an inactive inventory"""
    try:
        i = Inventory.objects.get(id=inventoryid)
        name = i.name if i.name is not None else ""
        i.delete()
        messages.success(request, f"Inventur {name} erfolgreich gelöscht.")
    except Inventory.DoesNotExist:
        messages.error(request, "Die angeforderte Inventur existiert nicht.")
        return redirect('inventory')
    except Exception as e:
        messages.add_message(request, messages.ERROR, e)
        return redirect('inventory')

    return redirect('inventory')


@login_required(login_url='login')
@allowed_users(allowed_roles=['Schreiben - Inventur'], url='devices')
def fullpage_inventory(request):
    """Tab inventory in device fullpage"""
    if request.method == 'POST':
        already_in_inventory = request.POST.get('already_in_inventory')
        device_id = request.POST.get('device_id')
        info = request.POST.get('text')
        inventory = get_activeInventory()

        device = Device.objects.get(id=device_id)

        if already_in_inventory == "true":
            inventory.remove(device)
        else:
            inventory.inventoryitem_set.add(InventoryItem(item=device, info=info), bulk=False)

        context = {
            'base_info': {
              'id': device_id,
            },
            'tabs': {
                'administration': {
                    'content': get_administration(device),
                },
            }
        }

        return render(request, 'fullpage/inventory.html', context)


@login_required(login_url='login')
@allowed_users(allowed_roles=['Schreiben - Inventur'], url='inventory')
def inventory_change_device(request):
    """Adds a device to an inventory or removes the device from an inventory, if it was already catalogued"""
    if request.method == 'POST':
        device_id = request.POST.get('device_id')
        already_in_inventory = request.POST.get('inventory')
        inventory = get_activeInventory()

        device = Device.objects.get(id=device_id)

        if already_in_inventory == "true":
            inventory.remove(device)
        else:
            inventory.add(device)

        return HttpResponse(status=204)


@login_required(login_url='login')
@allowed_users(allowed_roles=['Schreiben - Inventur'], url='inventory')
def inventory_remove_device(request, inventoryid, deviceid):
    """Remove an device from an active inventory in the inventory view"""
    try:
        d = Device.objects.get(id=deviceid)
        i = Inventory.objects.get(id=inventoryid)
        i.remove(d)
    except Device.DoesNotExist:
        messages.error(request, "Das angeforderte Gerät existiert nicht.")
        return redirect('inventory_view', inventoryid=inventoryid)
    except Exception as e:
        messages.add_message(request, messages.ERROR, e)
        return redirect('inventory_view', inventoryid=inventoryid)

    messages.success(request, f"Gerät erfolgreich entfernt.")
    return redirect('inventory_view', inventoryid=inventoryid)


@login_required(login_url='login')
@allowed_users(allowed_roles=['Lesen - Verleih'], url='devices')
def loan_showAll(request):
    current_user = request.user

    active_loans = Loan.objects.filter(active=True).order_by('startdate')
    inactive_loans = Loan.objects.filter(active=False)

    active_buttons = [["Anzeigen", 'blue', 'loan_view', 'icons/ic_eye_24px.svg']]
    inactive_buttons = [["Anzeigen", 'blue', 'loan_view', 'icons/ic_eye_24px.svg']]
    page_buttons = []

    if current_user.hasGroup("Schreiben - Verleih"):
        active_buttons.append(["Rückgabe", 'green', 'loan_return', 'icons/ic_publish_24px.svg'])
        inactive_buttons.append(["Löschen", 'red', 'loan_delete', 'icons/x.svg'])
        page_buttons.append(["Verleih/Reparatur hinzufügen", 'loan_create', 'icons/ic_add_24px.svg'])

    due = False

    for l in active_loans:
        if l.is_due(): due = True
    if due:
        messages.error(request, "Rot markierte Verleihelemente sind überfällig.")

    context = {
        'active_loans': active_loans,
        'inactive_loans': inactive_loans,
        'main_title': "Verleih und Reparatur",
        'active_buttons': active_buttons,
        'inactive_buttons': inactive_buttons,
        'page_buttons': page_buttons,
    }

    return render(request, 'inventory/overview/loan_list.html', context)


@login_required(login_url='login')
@allowed_users(allowed_roles=['Lesen - Verleih'], url='devices')
def loan_view(request, loanid):
    try:
        current_loan = Loan.objects.get(id=loanid)
    except ObjectDoesNotExist as e:
        raise Http404

    if current_loan.type == 'loan':
        title = f"Verleih vom {current_loan.startdate.strftime('%d.%m.%Y')} an {current_loan.loaned_to}"
    else:
        title = f"Reparatur vom {current_loan.startdate.strftime('%d.%m.%Y')}"

    context = {
        'loan': current_loan,
        'current_time': timezone.now(),
        'main_title': title,
        'page_buttons': [["Übersicht - Verleih", 'loan']],
    }

    return render(request, 'inventory/loan.html', context)


@login_required(login_url='login')
@allowed_users(allowed_roles=['Schreiben - Verleih'], url='loan')
def loan_return(request, loanid):
    try:
        l = Loan.objects.get(id=loanid)
        l.end_loan()
    except Loan.DoesNotExist:
        messages.error(request, "Der angeforderte Verleih existiert nicht.")
        return redirect('loan')
    except Exception as e:
        messages.add_message(request, messages.ERROR, e)
        return redirect('loan')

    messages.success(request, f"Rückgabe abgeschlossen.")
    return redirect('loan')


@login_required(login_url='login')

templates/inventory/overview/inventory_list.html
{% extends 'base/base.html' %}
{% load user_tags %}

{% block page_buttons %}
    {% if not already_active and user|has_group:"Schreiben - Inventur" %}
        <a href="#" class="dropdown_anchor"
           onclick="toggleDropDownClick('dropdownInventory')">{% include 'icons/ic_add_24px.svg' %} Neue Inventur</a>
        <form action="{% url 'inventory_create' %}" id="dropdownInventory" class="dropdownLogin-form" method="POST">
            {% csrf_token %}
            <label for="id_name">Anmerkung</label><br>
            <input type="text" name="name" id="inputName" class="form-control" placeholder="Anmerkung"
                   autofocus><br>
            <button type="submit" class="btn btn-sucess">
                Erstellen
            </button>
        </form>
    {% endif %}
{% endblock %}

{% block content %}
    {% include 'modal/delete.html' %}
    {% if active_inventories|length > 0 %}
        <table class="alternating_list">
            <caption>Aktive Inventur:</caption>
            <thead>
            <tr>
                <th scope="col">Gestartet von</th>
                <th scope="col">Startdatum</th>
                <th scope="col">Enddatum</th>
                <th scope="col">Anmerkung</th>
                <th scope="col">Aktionen</th>
            </tr>
            </thead>
            <tbody>
            {% for i in active_inventories reversed %}
                <tr>
                    <td data-label="Gestartet von">{{ i.started_by.username|default:"<i>Nutzer gelöscht</i>" }}</td>
                    <td data-label="Startdatum">{{ i.startdate }}</td>
                    <td data-label="Enddatum">{{ i.enddate|default:"<i>In Durchführung</i>" }}</td>
                    <td data-label="Anmerkung">{{ i.name|default:"<i>Keine Anmerkung</i>" }}</td>
                    <td data-label="Aktionen">
                        {% if active_buttons %}
                            <div>
                                {% for button in active_buttons %}
                                    {% if button.2 == 'inventory_end' %}
                                        <button id="confirm_deletion" value="{% url button.2 i.id %}"
                                                class="{{ button.1 }} underline_button"
                                                onclick="customConfirm(this, 'Inventur wirklich beenden?', 'Beenden')">
                                            {% if button|length > 3 %}
                                                {% include button.3 %}{% endif %}{{ button.0 }}
                                        </button>
                                    {% else %}
                                        <a id="{{ button.2 }}" class="{{ button.1 }} underline_button" href="{% url button.2 i.id %}">
                                            {% if button|length > 3 %}
                                                {% include button.3 %}{% endif %}{{ button.0 }}</a>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}
    {% if inactive_inventories|length > 0 %}
        <table class="alternating_list">
            <caption>Vorherige Inventuren:</caption>
            <thead>
            <tr>
                <th scope="col">Gestartet von</th>
                <th scope="col">Startdatum</th>
                <th scope="col">Enddatum</th>
                <th scope="col">Anmerkung</th>
                <th scope="col">Aktionen</th>
            </tr>
            </thead>
            <tbody>
            {% for i in inactive_inventories reversed %}
                <tr>
                    <td data-label="Gestartet von">{{ i.started_by.username }}</td>
                    <td data-label="Startdatum">{{ i.startdate }}</td>
                    <td data-label="Enddatum">{{ i.enddate|default:"In Durchführung" }}</td>
                    <td data-label="Anmerkung">{{ i.name|default:"<i>Keine Anmerkung</i>" }}</td>
                    <td data-label="Aktionen">
                        {% if inactive_buttons %}
                            <div>
                                {% for button in inactive_buttons %}
                                    {% if button.2 == 'inventory_delete' %}
                                        <button id="confirm_deletion" value="{% url button.2 i.id %}"
                                                class="{{ button.1 }} underline_button"
                                                onclick="customConfirm(this, 'Inventur wirklich löschen?', 'Löschen')">
                                            {% if button|length > 3 %}
                                                {% include button.3 %}{% endif %}{{ button.0 }}
                                        </button>
                                    {% else %}
                                        <a id="{{ button.2 }}" class="{{ button.1 }} underline_button" href="{% url button.2 i.id %}">
                                            {% if button|length > 3 %}
                                                {% include button.3 %}{% endif %}{{ button.0 }}</a>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}
{% endblock %}

templates/inventory/overview/loan_list.html
{% extends "base/base.html" %}

{% block content %}
    {% include 'modal/delete.html' %}
    {% if active_loans|length > 0 %}
        <table class="alternating_list">
            <caption>Aktuell verliehen:</caption>
            <thead>
            <tr>
                <th scope="col">Typ</th>
                <th scope="col">Verliehen von</th>
                <th scope="col">Verliehen an</th>
                <th scope="col">Verleihdatum</th>
                <th scope="col">Rückgabedatum</th>
                <th scope="col">Aktionen</th>
            </tr>
            </thead>
            <tbody>
            {% for i in active_loans reversed %}
                <tr {% if i.is_due %}class="due"{% endif %}>
                    <td data-label="Typ">
                        {% if i.type == 'loan' %}
                            {% include 'icons/basket2-fill.svg' %}
                        {% else %}
                            {% include 'icons/tools.svg' %}
                        {% endif %}
                    </td>
                    <td data-label="Verliehen von">{{ i.loaned_by.username|default:"<i>Nutzer gelöscht</i>" }}</td>
                    <td data-label="Verliehen an">
                        {% if i.type == 'loan' %}{{ i.loaned_to }}
                        {% else %}<i>E-Werkstatt</i>
                        {% endif %}
                    </td>
                    <td data-label="Verleihdatum">{{ i.startdate }}</td>
                    <td data-label="Rückgabedatum">
                        {% if i.type == 'loan' %}{{ i.enddate }}
                        {% else %}<i>in Reparatur</i>
                        {% endif %}
                    </td>
                    <td data-label="Aktionen">
                        {% if active_buttons %}
                            <div>
                                {% for button in active_buttons %}
                                    {% if button.2 == 'loan_return' %}
                                        <button id="confirm_deletion" value="{% url button.2 i.id %}"
                                                class="{{ button.1 }} underline_button"
                                                onclick="customConfirm(this, 'Verleih wirklich zurückgeben?', 'Rückgabe')">
                                            {% if button|length > 3 %}
                                                {% include button.3 %}{% endif %}{{ button.0 }}
                                        </button>
                                    {% else %}
                                        <a id="{{ button.2 }}" class="{{ button.1 }} underline_button" href="{% url button.2 i.id %}">
                                            {% if button|length > 3 %}
                                                {% include button.3 %}{% endif %}{{ button.0 }}</a>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}
    {% if inactive_loans|length > 0 %}
        <table class="alternating_list">
            <caption>Historie:</caption>
            <thead>
            <tr>
                <th scope="col">Verliehen von</th>
                <th scope="col">Verliehen an</th>
                <th scope="col">Verleihdatum</th>
                <th scope="col">Rückgabedatum</th>
                <th scope="col">Aktionen</th>
            </tr>
            </thead>
            <tbody>
            {% for i in inactive_loans reversed %}
                <tr>
                    <td data-label="Verliehen von">{{ i.loaned_by.username|default:"Nutzer gelöscht" }}</td>
                    <td data-label="Verliehen an">
                        {% if i.type == 'loan' %}{{ i.loaned_to }}
                        {% else %}<i>E-Werkstatt</i>
                        {% endif %}
                    </td>
                    <td data-label="Verleihdatum">{{ i.startdate }}</td>
                    <td data-label="Rückgabedatum">{{ i.enddate }}</td>
                    <td data-label="Aktionen">
                        {% if inactive_buttons %}
                            <div>
                                {% for button in inactive_buttons %}
                                    {% if button.2 == 'loan_delete' %}
                                        <button id="confirm_deletion" value="{% url button.2 i.id %}"
                                                class="{{ button.1 }} underline_button"
                                                onclick="customConfirm(this, 'Verleih wirklich löschen?', 'Löschen')">
                                            {% if button|length > 3 %}
                                                {% include button.3 %}{% endif %}{{ button.0 }}
                                        </button>
                                    {% else %}
                                        <a id="{{ button.2 }}" class="{{ button.1 }} underline_button" href="{% url button.2 i.id %}">
                                            {% if button|length > 3 %}
                                                {% include button.3 %}{% endif %}{{ button.0 }}</a>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}

{% endblock %}